"""Export answers/briefs (markdown) to md, html, csv, or pptx files.

- html: full standalone page (markdown -> html, minimal styling).
- csv:  extracts markdown tables; if the text has none, falls back to one
        row per bullet/paragraph so the export is never empty.
- pptx: H1/H2 headings become slides; bullets/paragraphs become slide body.
"""

from __future__ import annotations

import csv
import io
import re
from datetime import datetime, timezone
from pathlib import Path

FORMATS = ("md", "html", "csv", "pptx")

_HTML_PAGE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ font-family: "Segoe UI", system-ui, sans-serif; max-width: 860px;
         margin: 2rem auto; padding: 0 1rem; line-height: 1.55; color: #1c2530; }}
  table {{ border-collapse: collapse; }} th, td {{ border: 1px solid #ccc; padding: 4px 10px; }}
  code {{ background: #f2f4f6; padding: 1px 4px; border-radius: 4px; }}
  blockquote {{ color: #5c6874; border-left: 3px solid #ccc; margin-left: 0; padding-left: 1rem; }}
</style>
</head>
<body>
{body}
<hr><p><small>Generated by QuickJoiner on {date}.</small></p>
</body>
</html>
"""


def markdown_tables(md: str) -> list[list[list[str]]]:
    """Extract every markdown table as rows of cells (separator rows dropped)."""
    tables: list[list[list[str]]] = []
    current: list[list[str]] = []
    for line in md.splitlines():
        stripped = line.strip()
        if stripped.startswith("|") and stripped.endswith("|"):
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if all(re.fullmatch(r":?-{2,}:?", c) for c in cells):
                continue  # header separator row
            current.append(cells)
        elif current:
            tables.append(current)
            current = []
    if current:
        tables.append(current)
    return tables


def to_html(md: str, title: str) -> str:
    import markdown as md_lib

    body = md_lib.markdown(md, extensions=["tables", "fenced_code"])
    return _HTML_PAGE.format(
        title=title, body=body, date=datetime.now(timezone.utc).date().isoformat()
    )


def to_csv(md: str) -> str:
    out = io.StringIO()
    writer = csv.writer(out, lineterminator="\n")
    tables = markdown_tables(md)
    if tables:
        for i, table in enumerate(tables):
            if i:
                writer.writerow([])  # blank line between tables
            writer.writerows(table)
        return out.getvalue()
    # No tables: one row per meaningful line so the export still carries the content.
    writer.writerow(["content"])
    for line in md.splitlines():
        stripped = line.strip().lstrip("#*- ").strip()
        if stripped:
            writer.writerow([stripped])
    return out.getvalue()


def to_pptx(md: str, title: str, out_path: Path) -> None:
    from pptx import Presentation
    from pptx.util import Pt

    prs = Presentation()
    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = title
    title_slide.placeholders[1].text = (
        f"Generated by QuickJoiner · {datetime.now(timezone.utc).date().isoformat()}"
    )

    # Split into sections at H1/H2; each becomes one bulleted slide.
    sections: list[tuple[str, list[str]]] = []
    heading, lines = None, []
    for line in md.splitlines():
        m = re.match(r"^(#{1,2})\s+(.*)", line)
        if m:
            if heading or lines:
                sections.append((heading or title, lines))
            heading, lines = m.group(2).strip(), []
        else:
            stripped = line.strip()
            if stripped and not stripped.startswith("|"):
                lines.append(stripped.lstrip("*- ").strip())
    if heading or lines:
        sections.append((heading or title, lines))

    for section_title, bullets in sections:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = section_title
        body = slide.placeholders[1].text_frame
        body.clear()
        for i, bullet in enumerate(bullets[:12]):  # keep slides readable
            para = body.paragraphs[0] if i == 0 else body.add_paragraph()
            para.text = bullet[:220]
            para.font.size = Pt(16)
    prs.save(str(out_path))


def export_markdown(md: str, fmt: str, out_path: Path, title: str = "QuickJoiner answer") -> Path:
    """Write `md` to out_path in the requested format; returns the written path."""
    if fmt not in FORMATS:
        raise ValueError(f"Unknown format {fmt!r}. Formats: {', '.join(FORMATS)}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if fmt == "md":
        out_path.write_text(md, encoding="utf-8")
    elif fmt == "html":
        out_path.write_text(to_html(md, title), encoding="utf-8")
    elif fmt == "csv":
        out_path.write_text(to_csv(md), encoding="utf-8")
    elif fmt == "pptx":
        to_pptx(md, title, out_path)
    return out_path
