"""Backend contracts. `Catalog`/`PostgresCatalog` satisfy CatalogBackend;
`KnowledgeStore`/`PgVectorStore` satisfy StoreBackend. These Protocols document the
surface each backend must implement and let type-checkers verify parity; runtime
selection is duck-typed via memory/factory.py.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from quickjoiner.memory.store import SearchHit


@runtime_checkable
class CatalogBackend(Protocol):
    # config + sources
    def load_config(self): ...
    def save_config(self, config) -> None: ...
    def write_source(self, source) -> None: ...
    def list_source_configs(self) -> list: ...
    def upsert_source(self, source_id: str, name: str, type_: str, options: dict | None = ...) -> None: ...
    def list_sources(self) -> list[dict]: ...
    def delete_source(self, source_id: str) -> None: ...
    def get_setting(self, key: str) -> str | None: ...
    def set_setting(self, key: str, value: str) -> None: ...
    # documents
    def get_document_hash(self, doc_id: str) -> str | None: ...
    def get_document_graph_version(self, doc_id: str) -> int: ...
    def set_document_graph_version(self, doc_id: str, version: int) -> None: ...
    def upsert_document(self, doc_id, source_id, uri, title, kind, content_hash,
                        updated_at, chunk_count, graph_version: int = 0) -> None: ...
    def delete_document(self, doc_id: str) -> None: ...
    def stats(self) -> dict: ...
    # projects + sessions
    def upsert_project(self, project_id: str, name: str, description: str = ...) -> None: ...
    def get_project(self, id_or_name: str) -> dict | None: ...
    def list_projects(self) -> list[dict]: ...
    def save_session(self, session_id, project_id, title, summary, messages_json, est_tokens) -> None: ...
    def get_session(self, session_id: str) -> dict | None: ...
    def list_sessions(self, project_id: str | None = ...) -> list[dict]: ...
    # users + tokens
    def create_user(self, username: str, password_hash: str, role: str = ...) -> None: ...
    def get_user(self, username: str) -> dict | None: ...
    def set_user_role(self, username: str, role: str) -> None: ...
    def list_users(self) -> list[dict]: ...
    def count_users(self) -> int: ...
    def save_token(self, token_hash: str, username: str) -> None: ...
    def get_token_user(self, token_hash: str) -> str | None: ...
    def delete_token(self, token_hash: str) -> None: ...
    # knowledge graph
    def upsert_entity(self, entity_id: str, name: str, type_: str, source_id: str = ...) -> None: ...
    def add_entity_alias(self, alias: str, entity_id: str) -> None: ...
    def replace_doc_edges(self, evidence_doc_id: str, edges: list[tuple]) -> None: ...
    def resolve_entity(self, text: str) -> dict | None: ...
    def graph_neighbors(self, entity_id: str) -> list[dict]: ...
    def graph_path(self, src_id: str, dst_id: str, max_hops: int = ...) -> list[dict] | None: ...
    def graph_snapshot(self, entity_id: str | None = ..., limit: int = ...) -> dict: ...
    def graph_expand(self, seed_doc_ids: list[str], limit: int = ...) -> list[dict]: ...
    # knowledge-debt backlog
    def log_gap(self, query: str, best_score: float, nearest: list,
                session_id: str = ..., store_query: bool = ...) -> None: ...
    def list_gaps(self, status: str = ...) -> list[dict]: ...
    def resolve_gaps(self, gap_ids: list[str], resolution: str) -> None: ...
    # sync state
    def get_sync_state(self, source_id: str) -> dict[str, str]: ...
    def set_sync_state(self, source_id: str, key: str, value: str) -> None: ...
    def set_sync_state_many(self, source_id: str, state: dict[str, str]) -> None: ...
    def close(self) -> None: ...


@runtime_checkable
class StoreBackend(Protocol):
    @property
    def embedder(self): ...  # the Embedder used for this store (for query clustering, etc.)
    def upsert_document(self, doc_id, source_id, uri, title, kind, chunks,
                        updated_at: str = ...) -> int: ...
    def delete_document(self, doc_id: str) -> None: ...
    def delete_source(self, source_id: str) -> None: ...
    # `scope` (memory.store.SearchScope) restricts the search to given sources/documents,
    # filtered before ranking in both legs. Omitted/empty = the whole corpus.
    def search(self, query: str, top_k: int = ..., min_score: float = ...,
               scope=None) -> list[SearchHit]: ...
    def get_document_chunks(self, doc_id: str) -> list[str]: ...
    def get_documents_chunks(self, doc_ids: list[str]) -> dict[str, list[str]]: ...
